application: meetcharlottechen2
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /css
  static_dir: css
  
- url: /fonts
  static_dir: fonts
  
- url: /file
  static_dir: file
  
- url: /.*
  script: main.app